def freqWords(dna, k):
	global list1;
	list1 = [];
	i = 0; index = 0;
	currCount = 0;
	count = 0;
	countArray = [];
	for i in range(0,len(dna)-k):
		pattern = dna[i:(i+k)];
		countArray.append(Count(dna,pattern));
	maxCount = max(countArray);
	
	for i in range(0, len(dna)-k):
		pattern = dna[i:(i+k)];
		if maxCount == countArray[i]:
			list1.append(pattern)

	list1 = list(set(list1))
	print " ".join(list1)
	return list1;

def Count(text, pattern):
	count = 0; 
	strLength = len(text) - len(pattern);

	for i in range(0,strLength):
		substr = text[i:len(pattern) + i];
		if substr == pattern:
			count = count+1;
		i = i+1;
	return count;


freqWords("AGTACACTGTGGACCCGGGCAAGCCGGGCAAGCAGTACACTTCTCACCAGTACACAGTACACTGTGGACCTGTGGACCAGTACACTTCTCACCTGTGGACCTGTGGACCTTCTCACCAGTACACTCACTATTAAGTACACTTCTCACCAGTACACTTCTCACCTTCTCACCAGTACACTCACTATTATCACTATTATTCTCACCTCACTATTATCACTATTACGGGCAAGCTGTGGACCCGGGCAAGCTCACTATTATTCTCACCCGGGCAAGCAGTACACTTCTCACCTCACTATTATCACTATTAAGTACACTGTGGACCTCACTATTATCACTATTATGTGGACCTTCTCACCTGTGGACCCGGGCAAGCTCACTATTATGTGGACCTCACTATTATGTGGACCAGTACACTCACTATTACGGGCAAGCTCACTATTATGTGGACCAGTACACCGGGCAAGCCGGGCAAGCTGTGGACCAGTACACTTCTCACCTTCTCACCAGTACACCGGGCAAGCTCACTATTAAGTACACTCACTATTATTCTCACCTCACTATTATGTGGACCTGTGGACCAGTACACAGTACACCGGGCAAGCTCACTATTAAGTACACAGTACACAGTACACTGTGGACCCGGGCAAGCTTCTCACCTTCTCACCTCACTATTACGGGCAAGCAGTACACTGTGGACCTTCTCACCAGTACACCGGGCAAGCTTCTCACCTGTGGACCCGGGCAAGCTTCTCACCTCACTATTAAGTACACAGTACACTTCTCACCTGTGGACC", 13)
